package org.jetc.aeron.quick.server;

import org.jetc.aeron.quick.annotations.AeronQuickReceiver;
import org.jetc.aeron.quick.server.precompile.ReceiverAdapterBase;

import java.lang.reflect.InvocationTargetException;
import java.util.Optional;

public class Adapters {
    private static final String ADAPTER_SUFFIX = "_Adapter";

    /**
     * Loads and retrieves an adapter for a class marked with {@link AeronQuickReceiver @AeronQuickServer} which will bind the stream and channels to the corresponding method
     * @param targetServer to adapt with the compile time generated adapter
     * @return the corresponding server adapter for the targetServer or null if the class wasn't marked with {@link AeronQuickReceiver @AeronQuickServer}
     * @param <T> Any class marked with {@link AeronQuickReceiver @AeronQuickServer}
     */
    @SuppressWarnings("unchecked")
    public static <T> Optional<ReceiverAdapterBase<T>> adapt(T targetServer){
        Class<T> serverClass = (Class<T>) targetServer.getClass();

        if(serverClass.getAnnotation(AeronQuickReceiver.class) != null) {
            try {
                return Optional.of(
                        (ReceiverAdapterBase<T>) Class.forName(serverClass.getCanonicalName() + ADAPTER_SUFFIX)
                                .getDeclaredConstructor(serverClass)
                                .newInstance(targetServer)
                );
            } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException |
                     InstantiationException | IllegalAccessException ignored) {
                // IF THE CLASS IS MARKED WITH @AeronQuickServer IT WILL ALWAYS HAVE AN ADAPTER GENERATED BY THE PROCESSOR IN THE SAME PACKAGE
            }
        }
        return Optional.empty();
    }
}
