package org.jetc.aeron.quick.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * The method marked with this annotation will be bound to an Aeron internal buffer to receive or send content through it.
 * Depending on if it is in a class marked with {@link AeronQuickReceiver @AeronQuickServer} or
 * generated by AeronQuick through {@link org.jetc.aeron.quick.AeronQuickFactory#getClientBuilder(Class contract)}
 */
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface UnicastMessage {
    int streamID() default 0;
}